# Generated by Django 6.0.5 on 2026-05-18 12:45

import app.models.base_api_model
import django.contrib.postgres.functions
import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_comment="UUID for each record",
                        db_default=django.contrib.postgres.functions.RandomUUID(),
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Creation timestamp",
                        db_default=django.db.models.functions.datetime.Now(),
                        db_index=True,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Last update timestamp",
                        db_default=django.db.models.functions.datetime.Now(),
                        db_index=True,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        db_comment="Soft deletion timestamp",
                        db_default=None,
                        db_index=True,
                        null=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_comment="Name of the user", db_index=True, max_length=256
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("SUSPENDED", "Suspended"),
                            ("DELETED", "Deleted"),
                        ],
                        db_comment="Status of this user EX: ACTIVE, SUSPENDED, DELETED",
                        db_default="ACTIVE",
                        db_index=True,
                        default="ACTIVE",
                        max_length=64,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_comment="Email of the user", max_length=254, unique=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("password", models.CharField(max_length=128, null=True)),
                (
                    "profile_image",
                    models.JSONField(db_comment="Profile image of the user", null=True),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "users",
                "db_table_comment": "Users table",
                "ordering": ["created_at"],
                "get_latest_by": "created_at",
            },
            bases=(models.Model, app.models.base_api_model.BaseApiModel),
        ),
        migrations.CreateModel(
            name="ApiKey",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        db_comment="UUID for each record",
                        db_default=django.contrib.postgres.functions.RandomUUID(),
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Creation timestamp",
                        db_default=django.db.models.functions.datetime.Now(),
                        db_index=True,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Last update timestamp",
                        db_default=django.db.models.functions.datetime.Now(),
                        db_index=True,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        db_comment="Soft deletion timestamp",
                        db_default=None,
                        db_index=True,
                        null=True,
                    ),
                ),
                (
                    "prefix",
                    models.CharField(
                        db_comment="Unhashed prefix for identification (e.g. ubk_a1b2c3d4)",
                        db_index=True,
                        max_length=16,
                    ),
                ),
                (
                    "hashed_key",
                    models.CharField(
                        db_comment="SHA-256 hash of the full API key",
                        max_length=128,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_comment="Human-readable label for this key",
                        default="Default",
                        max_length=128,
                    ),
                ),
                (
                    "scopes",
                    models.JSONField(
                        db_comment="List of permission scopes (READ, WRITE)",
                        default=list,
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        db_comment="Last time this key was used to authenticate",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_comment="Owner of this API key",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "API Key",
                "verbose_name_plural": "API Keys",
                "db_table": "api_keys",
                "db_table_comment": "User API keys for programmatic access",
                "ordering": ["-created_at"],
                "get_latest_by": "created_at",
            },
            bases=(models.Model, app.models.base_api_model.BaseApiModel),
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        db_comment="UUID for each record",
                        db_default=django.contrib.postgres.functions.RandomUUID(),
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Creation timestamp",
                        db_default=django.db.models.functions.datetime.Now(),
                        db_index=True,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Last update timestamp",
                        db_default=django.db.models.functions.datetime.Now(),
                        db_index=True,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        db_comment="Soft deletion timestamp",
                        db_default=None,
                        db_index=True,
                        null=True,
                    ),
                ),
                (
                    "queue",
                    models.CharField(
                        db_comment="Queue name", db_index=True, max_length=256
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TODO", "Todo"),
                            ("IN_PROGRESS", "In Progress"),
                            ("DONE", "Done"),
                            ("FAILED", "Failed"),
                            ("WAITING", "Waiting"),
                            ("STOP", "Stop"),
                        ],
                        db_comment="Status of the job",
                        db_default="TODO",
                        db_index=True,
                        default="TODO",
                        max_length=256,
                    ),
                ),
                (
                    "failed_reason",
                    models.TextField(
                        db_comment="Reason for the job failure", null=True
                    ),
                ),
                (
                    "payload",
                    models.JSONField(db_comment="Payload of the job", null=True),
                ),
                (
                    "available_at",
                    models.DateTimeField(
                        db_comment="Available at timestamp", db_index=True, null=True
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        db_comment="Started at timestamp", db_index=True, null=True
                    ),
                ),
                (
                    "progress",
                    models.FloatField(
                        db_comment="Progress of the job", db_index=True, null=True
                    ),
                ),
                (
                    "retries",
                    models.IntegerField(
                        db_comment="Number of retries", db_index=True, null=True
                    ),
                ),
                (
                    "attachments",
                    models.JSONField(
                        db_comment="Attachments related to the job", null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        db_comment="The job is running for this user",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Job",
                "verbose_name_plural": "Jobs",
                "db_table": "jobs",
                "db_table_comment": "Jobs table",
                "ordering": ["created_at"],
                "get_latest_by": "created_at",
            },
            bases=(models.Model, app.models.base_api_model.BaseApiModel),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["name"], name="user_name_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="user_email_idx"),
        ),
        migrations.AddIndex(
            model_name="apikey",
            index=models.Index(fields=["prefix"], name="apikey_prefix_idx"),
        ),
        migrations.AddIndex(
            model_name="apikey",
            index=models.Index(fields=["hashed_key"], name="apikey_hashed_key_idx"),
        ),
    ]
