"""
Django settings for PDNR project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from app.config.app import AppConfig
from app.config.database import DatabaseConfig
from app.config.celery import CeleryConfig
from app.config.redis import RedisConfig
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = AppConfig.SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = AppConfig.DEBUG

ALLOWED_HOSTS = AppConfig.ALLOWED_HOSTS


# Application definition

INSTALLED_APPS = [
    "django_celery_beat",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "app",
    "django_extensions",
    "rest_framework",
    "rest_framework_simplejwt",
    "corsheaders",
    "drf_spectacular",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "app.middleware.impersonation.ImpersonationMiddleware",
]

ROOT_URLCONF = "PDNR.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ]
        },
    }
]

WSGI_APPLICATION = "PDNR.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": DatabaseConfig.ENGINE,
        "NAME": DatabaseConfig.NAME,
        "USER": DatabaseConfig.USER,
        "PASSWORD": DatabaseConfig.PASSWORD,
        "HOST": DatabaseConfig.HOST,
        "PORT": DatabaseConfig.PORT,
    },
    "sqllite3": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    },
}

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": RedisConfig.URL,
        "KEY_PREFIX": RedisConfig.KEY_PREFIX,
        "TIMEOUT": 60 * 15,
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

AUTH_USER_MODEL = "app.User"

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = AppConfig.STATIC_URL
STATIC_ROOT = os.path.join(BASE_DIR, AppConfig.STATIC_ROOT)

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Celery settings
CELERY_BROKER_URL = CeleryConfig.BROKER_URL

# For django-celery-beat
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"

# For django storage
DEFAULT_FILE_STORAGE = "django.core.files.storage.FileSystemStorage"
# MEDIA_ROOT = str(BASE_DIR / (getattr(AppConfig, 'MEDIA_ROOT', 'storage/media/') or 'storage/media/'))
MEDIA_ROOT = os.path.join(BASE_DIR, AppConfig.MEDIA_ROOT)
MEDIA_URL = AppConfig.MEDIA_URL

CORS_ALLOW_ALL_ORIGINS = True  # For development only TODO

# Session configuration for cross-origin requests
SESSION_COOKIE_SECURE = False  # Set to True in production with HTTPS
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'  # Allows cross-origin requests
SESSION_COOKIE_AGE = 60 * 60 * 24 * 7  # 7 days
SESSION_SAVE_EVERY_REQUEST = True
SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # Use database for session storage
SESSION_COOKIE_DOMAIN = None  # Allow cookies for all domains in development

# CORS configuration for credentials
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    AppConfig.FRONTEND_URL
]

from app.config.throttling import ThrottlingConfig

throttlingEnabled = ThrottlingConfig.ENABLED
userThrottlingRate = ThrottlingConfig.USER_RATE
anonThrottlingRate = ThrottlingConfig.ANON_RATE

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "app.middleware.api_key_authentication.ApiKeyAuthentication",
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.BasicAuthentication", #TODO: remove in production 
    ),
    "DEFAULT_THROTTLE_CLASSES": (
        [
            "rest_framework.throttling.AnonRateThrottle",
            "rest_framework.throttling.UserRateThrottle",
        ]
        if throttlingEnabled
        else None
    ),
    "DEFAULT_THROTTLE_RATES": {
        "anon": anonThrottlingRate,  # Anonymous users throttle rate
        "user": userThrottlingRate,  # Authenticated users throttle rate
    },
    "EXCEPTION_HANDLER": "app.exceptions.app_exceptions.app_exceptions_exception_handler",
}

from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=7),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),
    "USER_ID_FIELD": "uuid",
}
SPECTACULAR_SETTINGS = {
    "TITLE": "PDNR",
    "DESCRIPTION": "Api documentation for PDNR",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "SWAGGER_UI_SETTINGS": {"persistAuthorization": True, "docExpansion": "none"},
    "POSTPROCESSING_HOOKS": [
        "app.utils.openapi_tags.auto_tag_by_path_segment",
    ],
    "EXTENSIONS": [
        "app.middleware.api_key_authentication.ApiKeyAuthenticationScheme",
    ],
}
